problem:
  name: "conv_diff_2D_1C"

model:
  type: FNN
  params:
    hidden_layers: [64, 64, 64, 64, 64, 64, 64, 64, 64]
    # sigma: 1.0
    # encoding_dim: 64

model_target:
  _target_: multipinn.neural_network.${model.type}

regularization:
  type: Normal # Pointwise, Constant, Gradient, Normal, null
  params:
    alpha: 0.9
    # lambdas: [1, 1, 1, 1]

regularization_target:
  _target_: multipinn.regularization.${regularization.type}Losses

generator:
  domain_points: 20_000
  bound_points: 2_000
  sampler: "pseudo"

trainer:
  num_epochs: 100_000
  grid_update: 20_000
  random_seed: 42
  calc_loss: "mean" # "mean", "legacy"

visualization:
  grid_plot_points: 5000
  save_period: 5000
  save_mode: "png"

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.9999

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001

paths:
  save_dir: ${hydra:runtime.cwd}/examples/${problem.name}/artifacts/${model.type}_reg_${regularization.type}_loss_${trainer.calc_loss}
