problem:
  name: "heat_2D_CG"

model:
  type: FNN
  params:
    hidden_layers: [128, 128, 128, 128]

model_target:
  _target_: multipinn.neural_network.${model.type}

regularization:
  type: Constant # Pointwise, Constant, Gradient, Normal, null
  params:
    # ignored_indexes: [0]
    lambdas: [1, 10, 10, 10, 100]

regularization_target:
  _target_: multipinn.regularization.${regularization.type}Losses

generator:
  domain_points: 50_000
  bound_points: 5_000
  init_points: 10_000
  sampler: "pseudo"

trainer:
  num_epochs: 150_000
  grid_update: 200_000
  random_seed: 42
  calc_loss: "mean" # "mean", "legacy"

visualization:
  grid_plot_points: 20_000
  save_period: 2000
  save_mode: "html"

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.99997

optimizer:
  _target_: torch.optim.Adam
  lr: 0.005

paths:
  save_dir: ${hydra:runtime.cwd}/examples/${problem.name}/artifacts/${model.type}_${regularization.type}
  data: ${hydra:runtime.cwd}/examples/${problem.name}/data/heat_complex.dat
